[package]
name = "rawrgs"
version = "0.2.0"
edition = "2021"

[lib]
name = "rawrgs"
path = "src/lib.rs"

[[bin]]
name = "rawrgs_test"
path = "src/bin/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
